# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git checkout $(Build.SourceBranchName)
      echo YEE $(pat)
      git remote add heroku https://heroku:$(pat)@git.heroku.com/jaes-website.git
      git push heroku $(Build.SourceBranchName)
      npm install
      echo Adding code for raspberry
      sshpass -p 'rednanoj' ssh pi@jonbul.ddns.net
      pkill node
      npm install
      cd game/Jaes
      git fetch
      git pull
      node server.js
