version: "3.8"

services:
  app:
    build: .
    container_name: jaes-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/jonbul.ddns.net:/etc/letsencrypt/live/jonbul.ddns.net:ro
